### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by livingloves** [ibelem/webnnmeeting#5]
I am Getting This Error While Stating the Server

```
root@jisu-Conv:/home/jisu_admin/webnnmeeting# npm run start

> webnnmeeting@1.0.0 start /home/jisu_admin/webnnmeeting
> concurrently "nodemon server/meetingserver.js" "cross-env NODE_ENV=production node server/index.js"

[0] [nodemon] 2.0.4
[0] [nodemon] to restart at any time, enter `rs`
[0] [nodemon] watching path(s): *.*
[0] [nodemon] watching extensions: js,mjs,json
[0] [nodemon] starting `node server/meetingserver.js`
[0] sampleRoom Id: 5f7f142cb6e9f12ecafb1afa
[0] WebNN Meeting Rest API Server HTTPS Port: 8081
[1] WebNN Meeting App HTTPS Port: 8888
[1]
[1]  ERROR  Renderer resources are not loaded! Please check possible console errors and ensure dist (/home/jisu_admin/we                            bnnmeeting/.nuxt/dist/server) exists.
[1]
[1]   at VueRenderer.renderRoute (node_modules/@nuxt/vue-renderer/dist/vue-renderer.js:4400:17)
[1]   at VueRenderer.renderRoute (node_modules/@nuxt/vue-renderer/dist/vue-renderer.js:4388:21)
[1]   at async nuxtMiddleware (node_modules/@nuxt/server/dist/server.js:156:20)
[1]
 ERROR  Renderer resources are not loaded! Please check possible console errors and ensure dist (/home/jisu_admin/we                            bnnmeeting/.nuxt/dist/server) exists.
```

**Comment by ibelem** [comment]
@livingloves 

How about 

```
$ npm install
$ npm run dev
```

? 

Did you run `$ npm run build` before the `npm run start`?

**Comment by livingloves** [comment]
No I Didnot run` $ npm run build` before the `npm run start`

**Comment by ibelem** [comment]
@livingloves  Please run  `$ npm run build` at first:

```
Built at: 10/13/2020 8:34:52 AM
               Asset       Size  Chunks             Chunk Names
      pages/index.js   22.9 KiB       1  [emitted]  pages/index
       pages/perf.js     10 KiB       2  [emitted]  pages/perf
   pages/user/_id.js    260 KiB       3  [emitted]  pages/user/_id
           server.js    677 KiB       0  [emitted]  app
server.manifest.json  383 bytes          [emitted]
 + 4 hidden assets
Entrypoint app = server.js server.js.map
Ready to run nuxt start
```

The `$npm run start` requires files above built from `$ npm run build`

**Comment by livingloves** [comment]
ok One thing Thje WebRTC Server and The Meeting Server should Have to be one System Or Different System ?

**Comment by livingloves** [comment]
i am Getting this Error 
```
root@jisu-Conv:/home/jisu_admin/webnnmeeting# npm run-script build

> webnnmeeting@1.0.0 build /home/jisu_admin/webnnmeeting
> nuxt build

ℹ Production build                                                                                                                                            20:55:03
ℹ Bundling for server and client side                                                                                                                         20:55:03
ℹ Target: server                                                                                                                                              20:55:03

 WARN  Manifest meta already provided!                                                                                                                        20:55:03


 WARN  You are using a low quality icon, use icon png. See https://pwa.nuxtjs.org/icon/                                                                       20:55:03

✔ Builder initialized                                                                                                                                         20:55:03
✔ Nuxt files generated                                                                                                                                        20:55:03

✖ Client
  Compiled with some errors in 16.52s

◯ Server



Hash: 5ac4574976f841dae520
Version: webpack 4.44.1
Time: 16526ms
Built at: 10/14/2020 8:55:23 PM
                     Asset       Size  Chunks               Chunk Names
              6.0af114e.js   4.43 KiB       6  [immutable]
                  LICENSES  450 bytes
            app.9f8ff48.js    317 KiB       1  [immutable]  app
         img/0.9aae671.jpg    936 KiB
    pages/index.5a6bcb8.js   10.2 KiB       2  [immutable]  pages/index
     pages/perf.97fe541.js   4.37 KiB       3  [immutable]  pages/perf
 pages/user/_id.9d78306.js    124 KiB       4  [immutable]  pages/user/_id
        runtime.45cf2a9.js   2.39 KiB       5  [immutable]  runtime
vendors/commons.cb348c4.js    203 KiB       0  [immutable]  vendors/commons
Entrypoint app = runtime.45cf2a9.js vendors/commons.cb348c4.js app.9f8ff48.js

ERROR in ./node_modules/bulma/bulma.sass (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-1-1!./node_modules/postcss-loader/src??ref--6-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-1-3!./node_modules/bulma/bulma.sass)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Missing binding /home/jisu_admin/webnnmeeting/node_modules/node-sass/vendor/linux-x64-72/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 12.x

Found bindings for the following environments:
  - Linux 64-bit with Node.js 8.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to download the binding for your current environment.
    at module.exports (/home/jisu_admin/webnnmeeting/node_modules/node-sass/lib/binding.js:15:13)
    at Object.<anonymous> (/home/jisu_admin/webnnmeeting/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at getDefaultSassImplementation (/home/jisu_admin/webnnmeeting/node_modules/sass-loader/dist/getDefaultSassImplementation.js:24:10)
    at getSassImplementation (/home/jisu_admin/webnnmeeting/node_modules/sass-loader/dist/getSassImplementation.js:19:72)
    at Object.loader (/home/jisu_admin/webnnmeeting/node_modules/sass-loader/dist/index.js:40:61)
 @ ./node_modules/bulma/bulma.sass 4:14-177
 @ ./.nuxt/App.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

ERROR in ./assets/css/main.scss (./node_modules/css-loader/dist/cjs.js??ref--7-oneOf-1-1!./node_modules/postcss-loader/src??ref--7-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--7-oneOf-1-3!./assets/css/main.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Missing binding /home/jisu_admin/webnnmeeting/node_modules/node-sass/vendor/linux-x64-72/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 12.x

Found bindings for the following environments:
  - Linux 64-bit with Node.js 8.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to download the binding for your current environment.
    at module.exports (/home/jisu_admin/webnnmeeting/node_modules/node-sass/lib/binding.js:15:13)
    at Object.<anonymous> (/home/jisu_admin/webnnmeeting/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at getDefaultSassImplementation (/home/jisu_admin/webnnmeeting/node_modules/sass-loader/dist/getDefaultSassImplementation.js:24:10)
    at getSassImplementation (/home/jisu_admin/webnnmeeting/node_modules/sass-loader/dist/getSassImplementation.js:19:72)
    at Object.loader (/home/jisu_admin/webnnmeeting/node_modules/sass-loader/dist/index.js:40:61)
 @ ./assets/css/main.scss 4:14-224
 @ ./.nuxt/App.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

 FATAL  Nuxt build error                                                                                                                                      20:55:23

  at WebpackBundler.webpackCompile (node_modules/@nuxt/webpack/dist/webpack.js:5535:21)
  at processTicksAndRejections (internal/process/task_queues.js:97:5)
  at async WebpackBundler.build (node_modules/@nuxt/webpack/dist/webpack.js:5484:5)
  at async Builder.build (node_modules/@nuxt/builder/dist/builder.js:5643:5)
  at async Object.run (node_modules/@nuxt/cli/dist/cli-build.js:109:7)
  at async NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-index.js:2810:7)


   ╭─────────────────────────────╮
   │                             │
   │   ✖ Nuxt Fatal Error        │
   │                             │
   │   Error: Nuxt build error   │
   │                             │
   ╰─────────────────────────────╯

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webnnmeeting@1.0.0 build: `nuxt build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webnnmeeting@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-14T15_25_23_040Z-debug.log
root@jisu-Conv:/home/jisu_admin/webnnmeeting#

```

**Comment by ibelem** [comment]
@livingloves Usually the WebRTC Server should be on a different host machine,  the server hardware capability e.g CPU/memory and network bandwidth decides the online users can be supported.

About the errors, this usually happens because your environment has changed since running `npm install`, how about to run `npm rebuild node-sass` or `npm i node-sass -D` at first then retry `$ npm run build`
